name: petbond_uk
description: A new Flutter project.
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  pusher_channels_flutter: ^2.1.2
  http: ^1.6.0
  string_validator: ^0.3.0
  path: ^1.9.1
  async: ^2.10.0
  flutter_svg: ^2.2.2
  webview_flutter: ^3.0.4
  country_picker: ^2.0.27
  dotted_border: ^3.1.0
  image_picker: ^0.8.5+3
  flutter_secure_storage: ^5.1.2
  flutter_overlay_loader: ^1.0.8
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.14.0
  google_maps_flutter_web: ^0.5.14+3
  geocoding: ^4.0.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/appbar_background.png
  fonts:
    - family: FredokaOne
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
# Enable web
flutter:
  uses-material-design: true
